import { NextPage } from 'next';
import Head from 'next/head';
import LandingPageTemplate from '../components/LandingPage/LandingPageTemplate';

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hat Bot Dashboard</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <LandingPageTemplate />
    </>
  );
};

export default Index;
