export const emojiList = [
  {
    id: '66218',
    name: 'hatCash',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306349956',
    name: 'hatApe',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_6b2d4f9d4a2c4bb78aff1c6ab33aca44',
    name: 'hatRipley',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_72079176c92a4fdcbc16d64180c695c6',
    name: 'hatMilk',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306313296',
    name: 'hatRip',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '303867988',
    name: 'hatTry',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306309588',
    name: 'hatLate',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '696249',
    name: 'hatMan',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '124649',
    name: 'hatX',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306349988',
    name: 'hatDolla',
    images: [Object],
    tier: '2000',
    emote_type: 'subscriptions',
    emote_set_id: '32359',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '300662651',
    name: 'hatMochi',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '696251',
    name: 'hatWay',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306269613',
    name: 'hatJarl',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '58829',
    name: 'hatL',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_c0f13b5f23524499a2c892d3e1461239',
    name: 'hatRainbow',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '359135697',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1414660',
    name: 'hatDOGEYES',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '64573',
    name: 'hatPepe',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_03280fec533945e7a4b192a4fee103f7',
    name: 'hatHuey',
    images: [Object],
    tier: '',
    emote_type: 'bitstier',
    emote_set_id: '961246567',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306277897',
    name: 'hatClown',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306349991',
    name: 'hatWaste',
    images: [Object],
    tier: '3000',
    emote_type: 'subscriptions',
    emote_set_id: '32360',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306349975',
    name: 'hatRich',
    images: [Object],
    tier: '3000',
    emote_type: 'subscriptions',
    emote_set_id: '32360',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '124647',
    name: 'hatF',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '70579',
    name: 'hatH',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '300407143',
    name: 'hatOface',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_56482e788262404e8e6316bdf0131feb',
    name: 'hatBall',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '359135697',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306349983',
    name: 'hatGold',
    images: [Object],
    tier: '2000',
    emote_type: 'subscriptions',
    emote_set_id: '32359',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '66216',
    name: 'hatFail',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '300696840',
    name: 'hatRandy',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '58828',
    name: 'hatS',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '70580',
    name: 'hatW2',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '300667106',
    name: 'hatRage',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306309579',
    name: 'hatChoc',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306309899',
    name: 'hatTech',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '57961',
    name: 'hatR',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1414687',
    name: 'hatPOG',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306349969',
    name: 'hatBrown',
    images: [Object],
    tier: '2000',
    emote_type: 'subscriptions',
    emote_set_id: '32359',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_e22b5e1d04ba464b84669753552cd0e1',
    name: 'hatCreepy',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '302985326',
    name: 'hatMurph',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306309640',
    name: 'hatSalmon',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1527612',
    name: 'hatN',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1414535',
    name: 'hatLUL',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1527611',
    name: 'hatY',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '696252',
    name: 'hatHoo',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306404310',
    name: 'hatKing',
    images: [Object],
    tier: '2000',
    emote_type: 'subscriptions',
    emote_set_id: '32359',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '70583',
    name: 'hatW4',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1527601',
    name: 'hatWierd',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1414542',
    name: 'hatWUT',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_b6505a360cb7446299e92859496d6f6c',
    name: 'hatGG',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306309662',
    name: 'hatSnac',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '307845901',
    name: 'hatFuzz',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_202413893f3f43f2a8666baab98097ee',
    name: 'hatTrotty',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '300885062',
    name: 'hatShook',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '57962',
    name: 'hatT',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306309595',
    name: 'hatBois',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: 'emotesv2_9a6cc02419da498bb6062f81c2b56462',
    name: 'hatSmuzz',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '359135697',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1414538',
    name: 'hatFAIL',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306330383',
    name: 'hatPride',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306269622',
    name: 'hatHyper',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306355041',
    name: 'hatBoik',
    images: [Object],
    tier: '3000',
    emote_type: 'subscriptions',
    emote_set_id: '32360',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306330390',
    name: 'hatWave',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '1527359',
    name: 'hatWOW',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '70581',
    name: 'hatW1',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '70582',
    name: 'hatW3',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
  {
    id: '306269608',
    name: 'hatSmooth',
    images: [Object],
    tier: '1000',
    emote_type: 'subscriptions',
    emote_set_id: '13089',
    format: [Array],
    scale: [Array],
    theme_mode: [Array],
  },
];
